Update specMACS cloud geometry dataset
eurec4a/eurec4a-intake pull request #142
Opened 2023-08-09 12:44 UTC by lvol08

Update links for specMACS cloud geometry dataset and remove the old "experimental" dataset

2023-08-09 14:51 UTC, observingClouds commented
Thanks for the update @lvol08! Currently the test is failing but this is hopefully fixed after #143 is merged.

2023-08-10 17:14 UTC, observingClouds requested changes
Hi @lvol08,

The CI is now running successfully. I just left some minor comments here. I think after those are discussed we can merge this great amount of work 🥳 .

Could you also confirm that this does not affect any entries in the howto.eurec4a.eu book, e.g. because renaming/deletion etc.?

Cheers,
Hauke

2023-08-10 17:14 UTC, observingClouds commented on HALO/specmacs/geometrypoints.yaml
Looking at this file I have two small comments:
- [ ] From the description of the catalog entries I cannot figure out what the endings mean (`c1`, `rcw1`, `sl1`, `bc1`,...). It would be great if this would become clear from the description of the dataset.
- [ ] A hyphen in the catalog entries is sometimes interpreted as a minus sign making auto-completion tricky. `cat.HALO-0119_c1` is assumed to be a subtraction of `cat.HALO` and `0119_c1`. One could write `cat['HALO-0119_c1']` but I would prefer if both versions would work. Could you change the `-` to `_`?

2023-08-10 17:18 UTC, observingClouds commented on HALO/specmacs/geometrypoints.yaml
Ah, forget about my point about the minus sign. This is currently the standard for the HALO datasets and should be addressed at a different time.

2023-08-11 08:50 UTC, lvol08 commented on HALO/specmacs/geometrypoints.yaml
Hi @observingClouds,

thanks for the comments. I updated the CHANGELOG.md and the description of the datasets in [HALO/specmacs/geometrypoints.yaml](https://github.com/eurec4a/eurec4a-intake/pull/142/files/065e2ae03988b6718ee8b36c26e60983860b102d#diff-c06b614e150bc01aaad607d256a79064732d807361670dfcc746c31ec17d25bf). Hope that it is clearer now?!

And as far as I know there is no existing howto.eurec4a.eu entry for the specMACS cloud geometry yet, but I am currently working on one (just need to include the new links from the intake catalogue and will upload the book then).

Cheers,
Lea

2023-08-11 08:52 UTC, lvol08 commented
Hi @observingClouds,

thanks for the comments. I updated the CHANGELOG.md and the description of the datasets in [HALO/specmacs/geometrypoints.yaml](https://github.com/eurec4a/eurec4a-intake/pull/142/files/065e2ae03988b6718ee8b36c26e60983860b102d#diff-c06b614e150bc01aaad607d256a79064732d807361670dfcc746c31ec17d25bf). Hope that it is clearer now?!

And as far as I know there is no existing howto.eurec4a.eu entry for the specMACS cloud geometry yet, but I am currently working on one (just need to include the new links from the intake catalogue and will upload the book then).

Cheers,
Lea

2023-08-11 15:59 UTC, observingClouds approved these changes

2023-08-11 16:00 UTC, merged